# Generated by Django 5.0.6 on 2024-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('license_type', models.CharField(max_length=50)),
                ('date_purchased', models.DateField()),
                ('valid_upto', models.DateField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
